### ISSUE TITLE
일부 기능 추가

### ISSUE THREAD

**Issue by ds5105119** [Jungminchae/orm-study#36]
추가한 기능

1. 시험 모드를 추가했습니다. 시험 모드에서는 문제 개수만 선택할 수 있으며, 15문제 이상을 선택해야 합니다.
2.  start command를 사용 시 시험 모드를 켜고 끌 수 있게 바꿨습니다. 시험 모드를 실행하는 경우 ./ 위치에 시험 성적서 png 파일이 생성됩니다.

---

 <details>
<summary>수정 사항</summary>
orm_study/quiz/command.py 파일 수정
- TimeTrace Class Decorator 추가
- fetch_exam 함수 추가
- select_exam_mode 함수 추가
- fetch_quiz 함수 변경
- select_quiz_num 함수 변경: min_num 키워드가 추가되었습니다. 기본값은 1이며, min_num 이상의 값을 선택해야 합니다.
- solve_quiz 함수에 TimeTrace Decorator 추가 -> 반환 값: Tuple[List[bool], float]: solve_quiz의 반환값과 solve_quiz 함수의 실행 시간
- start 함수 변경: 시험 모드, 퀴즈 모드 선택 기능 추가, 시험 모드 선택 시 certification.py 내의 함수로 성적서 발급하는 로직 추가
- 몇몇 함수에 Google Style Python Docstrings 추가

orm_study/quiz/reader.py 파일 수정
- get_chapter 로직 수정

orm_study/script/certification.py 파일 추가
- pillow 모듈 사용
- generate_certification_image 함수 추가: 시험 성적서 PNG 파일 생성 함수

orm_study/quiz/_resources 폴더 추가
- 인증서 이미지 certification.png 추가
- 인증서 이미지 출력에 사용될 폰트 PretendardVariable.ttf 추가

orm_study/quiz/python.py 파일 수정
- PythonQuizManager Class의 solve 함수에서 solve_quiz 함수를 사용하므로, 반환받을 값 process_time를 추가

orm_study/tests/test_quiz_command.py 파일 수정
- test_solve_quiz 함수에서 solve_quiz를 사용하므로, 반환받을 값 process_time을 추가

requirements.txt 파일 수정
- pillow~=10.4.0 추가

requirements-dev.txt 파일 수정
- pillow~=10.4.0 추가
</details>

**Comment by Jungminchae** [comment]
시험 모드를 만들어주신다니 감사합니다
